CREATE TABLE public."Govt_Respnd_Tracker"
(
"CountryName" varchar(255),
"CountryCode" char(3),
"Date" DATE,
"C1_School closing" int,	
"C1_Flag" bit,
"C2_Workplace closing" int,
"C2_Flag"	bit,
"C3_Cancel public events" int,
"C3_Flag" bit,
"C4_Restrictions on gatherings" int,
"C4_Flag" bit,
"C5_Close public transport" int,
"C5_Flag" bit,
"C6_Stay at home requirements" int,
"C6_Flag" bit,
"C7_Restrictions on internal movement" int,
"C7_Flag" bit,
"C8_International travel controls" int,
"E1_Income support" int,
"E1_Flag" bit,
"E2_Debt/contract relief" int,
"E3_Fiscal measures" money,
"E4_International support" money,
"H1_Public information campaigns" int,
"H1_Flag" bit,
"H2_Testing policy" int,
"H3_Contact tracing" int,
"H4_Emergency investment in healthcare" money,
"H5_Investment in vaccines" money,
"M1_Wildcard" varchar(255),
"ConfirmedCases" bigint,
"ConfirmedDeaths" bigint,
"StringencyIndex" decimal(5,2),
"StringencyIndexForDisplay" decimal (5,2),
"StringencyLegacyIndex" decimal (5,2),
"StringencyLegacyIndexForDisplay" decimal (5,2),
"GovernmentResponseIndex" decimal (5,2),
"GovernmentResponseIndexForDisplay" decimal (5,2),
"ContainmentHealthIndex" decimal (5,2),
"ContainmentHealthIndexForDisplay" decimal (5,2),
"EconomicSupportIndex" decimal (3,2),
"EconomicSupportIndexForDisplay" decimal (3,2)
)